version: '3.3'
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
  #   volumes:
  #     - ./requirements/mariadb:var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rroland
  #     MYSQL_DATABASE: mariadb
  #     MYSQL_USER: rroland
    restart: always
    tty:
      true
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    networks:
      - my-net
    networks:
      - my-net
  #   volumes:
  #     - ./requirements/wordpress/wp-config.php:/var/www/html/wordpress
  #     - ./requirements/wordpress/config.inc.php://var/www/html/phpmyadmin
  #   environment:
  #     MYSQL_HOST: mariadb
  #   restart: always
    depends_on:
      - mariadb
    tty: true
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - my-net
    restart: always
    depends_on:
      - wordpress
      
    # volumes:
    #   - ./requirements/nginx/nginx.conf ./etc/nginx/sites-available

  networks:
    name: my-net
    # driver: bridge